name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "1Timo1"
        git config --global user.email "emailhere"
        git config pull.rebase false
        git pull
        rm -f BingoRPGomme.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'BingoRPGomme.zip'
        exclusions: '*.git* /*node_modules/* .editorconfi gui/*'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
