name: use this
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "1Timo1"
    - name: Install zip
      uses: montudor/action-zip@v1
      
#Light
    - name: Zip output LightRP
      run: zip -r release/BingoRPGommeLight.zip pack.png pack.mcmeta README.md assets -x assets/minecraft/textures/gui\*
      working-directory: .
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
  
    - uses: actions/upload-artifact@v3
      with:
        name: BingoRPGommeLight.zip
        path: release/BingoRPGommeLight.zip
        
  #Dark
    - name: Zip output DarkRP
      run: zip -r release/BingoRPGommeDark.zip pack.png pack.mcmeta README.md assets
      working-directory: .
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
        
    - uses: actions/upload-artifact@v3
      with:
        name: BingoRPGommeDark.zip
        path: release/BingoRPGommeDark.zip
