name: use this
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "1Timo1"
    - name: Install zip
      uses: montudor/action-zip@v1
      
#Light
    - name: Zip output LightRP
      run: zip -r release/BingoRPGommeLight.zip pack.png pack.mcmeta README.md assets -x assets/minecraft/textures/gui\*
      working-directory: .
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
  
    - uses: actions/upload-artifact@v3
      with:
        name: BingoRPGommeLight.zip
        path: release/BingoRPGommeLight.zip
        
  #Dark
    - name: Zip output DarkRP
      run: zip -r release/BingoRPGommeDark.zip pack.png pack.mcmeta README.md assets
      working-directory: .
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
        
    - uses: actions/upload-artifact@v3
      with:
        name: BingoRPGommeDark.zip
        path: release/BingoRPGommeDark.zip
        
    - name: Discord.js-Webhook
  # You may pin to the exact commit or the version.
  # uses: EhsanFox/djs-actions@16ddc097afad2b3b8c8913c4b56fbee4678a9d29
      uses: EhsanFox/djs-actions@0.1.0
      with:
        # Discord Webhook ID, for Users Safety, it should be stored in secrets of the Repo and inserted as a context expression.
        id: ${{ secrets.DCID }}
        # Discord Webhook Token, for Users Safety, it should be stored in secrets of the Repo and inserted as a context expression.
        token: ${{ secrets.DCTOKEN }}
        # Username of the Webhook
        username: Seelenverwandter
        # a URL for Discord Webhook Avatar, PNG only Allowed.
        avatar: https://cdn.discordapp.com/attachments/1056264822259458118/1056272281908826192/Komp_1.png
        # a Text to Be sent with the Webhook, it's not the embed.
        content: Hi
        # Title Text which would be on the embed
        title: Neues RP Update
        # URL of The title which is on the embed
        url: https://github.com/1Timo1/BingoRPGomme/tree/main/release
        # an Author Text which would be on the embed
        author: 1Timo1
        # Author Icon/Image that would be on the embed
        author_icon: https://cdn.discordapp.com/avatars/539902118576914435/a_2106e998bd168a9216c04f3a76f0e25c.png
        # URL of The author which is on the embed
        author_url: https://cdn.discordapp.com/avatars/539902118576914435/a_2106e998bd168a9216c04f3a76f0e25c.png
        # Footer Text that would be on the embed
        footer: Bla
        # Footer Icon/Image that would be on the embed
        footer_icon: https://cdn.discordapp.com/avatars/539902118576914435/a_2106e998bd168a9216c04f3a76f0e25c.png
        # Image that would be on the embed
        image: https://cdn.discordapp.com/attachments/1056264822259458118/1056272281908826192/Komp_1.gif
        # Image that would be on the embed as Thumbnail
        thumbnail: https://cdn.discordapp.com/attachments/1056264822259458118/1056272281908826192/Komp_1.gif
        # Hex Code of a Color that would be on the embed, it would be RANDOM if it's not provided
        color: ff0000
        # a Text for Description of Embed
        description: Blub        
