name: penner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "1Timo1"
    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
          type: 'zip'
          filename: 'rawproto-linux-i64.zip'
          directory: .
          exclusions: '*.git* /*node_modules/* .editorconfig *assets/minecraft/textures/gui/container* *.zip'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
