name: penner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "1Timo1"
    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -qq -r output.zip pack.mcmeta
      working-directory: .
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
