name: penner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'penner.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *assets/minecraft/textures/gui/container*'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
