name: penner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'penner.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *assets/minecraft/textures/gui/container*'
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Changed files
