name: penner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "1Timo1"
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.0
      with:
        type: 'zip'
        filename: 'penner.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *assets/minecraft/textures/gui/container*'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
